dist: xenial
sudo: required

before_script:
   - sudo apt-get -qq update
   - sudo apt-get install -qq build-essential cmake libfftw3-dev libmbedtls-dev libpcsclite-dev libboost-program-options-dev libconfig++-dev libsctp-dev

language: cpp
script:
 - mkdir build
 - cd build
 - cmake -DRF_FOUND=True ..
 - make
 - make test
 - sudo make install
